In [1]:
import numpy as np

In [2]:
np.set_printoptions(suppress=True, linewidth=100, precision=2)

In [3]:
def create_backup(file_name, headers, data):
    np.savez(file_name, headers=headers, data=data)
    return np.load(file_name + '.npz')

In [4]:
raw_data = np.genfromtxt('loan-data.csv', delimiter=';', skip_header=1)
print(raw_data)

[[48010226.           nan    35000.   ...         nan         nan     9452.96]
 [57693261.           nan    30000.   ...         nan         nan     4679.7 ]
 [59432726.           nan    15000.   ...         nan         nan     1969.83]
 ...
 [50415990.           nan    10000.   ...         nan         nan     2185.64]
 [46154151.           nan         nan ...         nan         nan     3199.4 ]
 [66055249.           nan    10000.   ...         nan         nan      301.9 ]]


In [5]:
np.isnan(raw_data).sum()

88005

In [6]:
temporary_fill = np.nanmax(raw_data).round(2) + 1
temporary_fill

68616520.0

In [7]:
temporary_stats = np.array([
    np.nanmin(raw_data, axis=0),
    np.nanmean(raw_data, axis=0),
    np.nanmax(raw_data, axis=0)
])
print(temporary_stats)

[[  373332.           nan     1000.           nan     1000.           nan        6.         31.42
          nan         nan         nan         nan         nan        0.  ]
 [54015809.19         nan    15273.46         nan    15311.04         nan       16.62      440.92
          nan         nan         nan         nan         nan     3143.85]
 [68616519.           nan    35000.           nan    35000.           nan       28.99     1372.97
          nan         nan         nan         nan         nan    41913.62]]


<ipython-input-7-1a07b759a163>:2: RuntimeWarning: All-NaN slice encountered
  np.nanmin(raw_data, axis=0),
<ipython-input-7-1a07b759a163>:3: RuntimeWarning: Mean of empty slice
  np.nanmean(raw_data, axis=0),
<ipython-input-7-1a07b759a163>:4: RuntimeWarning: All-NaN slice encountered
  np.nanmax(raw_data, axis=0)


In [8]:
str_col_ids = np.argwhere(np.isnan(temporary_stats[1])).squeeze()
print(str_col_ids)

[ 1  3  5  8  9 10 11 12]


In [9]:
numeric_col_ids = np.argwhere(np.isnan(temporary_stats[1]) == 0).squeeze()
print(numeric_col_ids)

[ 0  2  4  6  7 13]


In [10]:
loan_data_numeric = np.genfromtxt('loan-data.csv',
                                 delimiter=';',
                                 usecols = numeric_col_ids,
                                 skip_header = 1,
                                 filling_values = temporary_fill)
print(loan_data_numeric)

[[48010226.      35000.      35000.         13.33     1184.86     9452.96]
 [57693261.      30000.      30000.   68616520.        938.57     4679.7 ]
 [59432726.      15000.      15000.   68616520.        494.86     1969.83]
 ...
 [50415990.      10000.      10000.   68616520.   68616520.       2185.64]
 [46154151.   68616520.      10000.         16.55      354.3      3199.4 ]
 [66055249.      10000.      10000.   68616520.        309.97      301.9 ]]


In [11]:
loan_data_str = np.genfromtxt('loan-data.csv',
                             delimiter=';',
                             usecols = str_col_ids,
                             skip_header = 1,
                             dtype = np.str)
print(loan_data_str)

[['May-15' 'Current' ' 36 months' ... 'Verified'
  'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226' 'CA']
 ['' 'Current' ' 36 months' ... 'Source Verified'
  'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261' 'NY']
 ['Sep-15' 'Current' ' 36 months' ... 'Verified'
  'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726' 'PA']
 ...
 ['Jun-15' 'Current' ' 36 months' ... 'Source Verified'
  'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990' 'CA']
 ['Apr-15' 'Current' ' 36 months' ... 'Source Verified'
  'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151' 'OH']
 ['Dec-15' 'Current' ' 36 months' ... ''
  'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249' 'IL']]


<ipython-input-11-604b4808b20c>:5: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype = np.str)


In [12]:
all_headers = np.genfromtxt('loan-data.csv',
                            delimiter=';',
                            skip_footer = loan_data_numeric.shape[0],
                            dtype = np.str)
all_headers

<ipython-input-12-7b7481103241>:4: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype = np.str)


array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [13]:
numeric_headers = all_headers[numeric_col_ids]
numeric_headers

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [14]:
str_headers = all_headers[str_col_ids]
str_headers

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [15]:
loan_data_numeric_backup = create_backup('loan-data-numeric-backup', numeric_headers, loan_data_numeric)

In [16]:
loan_data_str_backup = create_backup('loan-data-str-backup', str_headers, loan_data_str)

In [17]:
loan_data_str[:,0]

array(['May-15', '', 'Sep-15', ..., 'Jun-15', 'Apr-15', 'Dec-15'], dtype='<U69')

### String - Issue Date column

In [18]:
str_headers[0] = 'issue_date'

In [19]:
np.unique(loan_data_str[:,0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [20]:
loan_data_str[:,0] = np.chararray.strip(loan_data_str[:,0], '-15')

In [21]:
np.unique(loan_data_str[:,0])

array(['', 'Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May', 'Nov', 'Oct', 'Sep'],
      dtype='<U69')

In [22]:
months = np.array(['', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'])

In [23]:
for i in range(13):
    loan_data_str[:,0] = np.where(loan_data_str[:,0] == months[i],
                                  i,
                                  loan_data_str[:,0])

In [24]:
np.unique(loan_data_str[:,0])

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

### String - Loan Status and Term

In [25]:
loan_data_str[:,1:3]

array([['Current', ' 36 months'],
       ['Current', ' 36 months'],
       ['Current', ' 36 months'],
       ...,
       ['Current', ' 36 months'],
       ['Current', ' 36 months'],
       ['Current', ' 36 months']], dtype='<U69')

In [26]:
np.unique(loan_data_str[:,1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [27]:
np.unique(loan_data_str[:,2])

array(['', ' 36 months', ' 60 months'], dtype='<U69')

In [28]:
loan_data_str[:,2] = np.chararray.strip(loan_data_str[:,2], ' months')
np.unique(loan_data_str[:,2])

array(['', '36', '60'], dtype='<U69')

In [29]:
loan_data_str[:,2] = np.where(loan_data_str[:,2] == '', 60, loan_data_str[:,2])
np.unique(loan_data_str[:,2])

array(['36', '60'], dtype='<U69')

In [30]:
str_headers[2] = 'term_months'

In [31]:
loan_status_default = np.array(['', 'Charged Off', 'Default', 'Late (31-120 days)'])

In [32]:
loan_data_str[:,1] = np.where(np.isin(loan_data_str[:,1], loan_status_default), 0, 1)

In [33]:
np.unique(loan_data_str[:,1])

array(['0', '1'], dtype='<U69')

### String - Grade and Sub-grade columns

In [34]:
loan_data_str[:,3:5]

array([['C', 'C3'],
       ['A', 'A5'],
       ['B', 'B5'],
       ...,
       ['A', 'A5'],
       ['D', 'D2'],
       ['A', 'A4']], dtype='<U69')

In [35]:
np.unique(loan_data_str[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [36]:
np.unique(loan_data_str[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

In [37]:
subgrade_empty_indices = np.argwhere(loan_data_str[:,4] == '').squeeze()

In [38]:
subgrade_empty_indices

array([  31,   32,   53,   75,   77,   81,   82,   87,  127,  132,  160,  178,  211,  222,  231,
        259,  267,  280,  284,  300,  324,  337,  345,  346,  357,  380,  392,  412,  462,  475,
        486,  520,  521,  535,  546,  552,  608,  631,  633,  643,  644,  647,  653,  658,  660,
        677,  695,  697,  708,  710,  741,  747,  748,  749,  782,  786,  790,  795,  879,  880,
        978,  983,  998, 1045, 1060, 1077, 1151, 1217, 1223, 1224, 1262, 1267, 1352, 1374, 1411,
       1420, 1424, 1473, 1542, 1560, 1615, 1649, 1654, 1718, 1719, 1721, 1727, 1731, 1799, 1803,
       1816, 1830, 1842, 1848, 1852, 1867, 1879, 1890, 1900, 2001, 2008, 2016, 2024, 2050, 2093,
       2094, 2105, 2109, 2115, 2126, 2164, 2231, 2269, 2328, 2340, 2349, 2373, 2399, 2400, 2414,
       2449, 2455, 2477, 2499, 2517, 2521, 2615, 2632, 2647, 2668, 2678, 2701, 2708, 2724, 2748,
       2775, 2781, 2782, 2831, 2841, 2890, 2919, 2932, 2975, 2992, 3001, 3011, 3019, 3039, 3040,
       3044, 3066, 3068, 3073,

In [39]:
loan_data_str[:,4] = np.where(loan_data_str[:,4] == '',
                              np.where(loan_data_str[:,3] != '', np.char.add(loan_data_str[:,3], '5'), ''),
                              loan_data_str[:,4])
np.unique(loan_data_str[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

In [40]:
loan_data_str[:,4] = np.where(loan_data_str[:,4] == '', 'H1', loan_data_str[:,4])
np.unique(loan_data_str[:,4])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

In [41]:
loan_data_str = np.delete(loan_data_str, [3], axis=1)

In [42]:
str_headers = np.delete(str_headers, [3])

In [43]:
str_headers

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [44]:
loan_data_str[0:5]

array([['5', '1', '36', 'C3', 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['0', '1', '36', 'A5', 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['9', '1', '36', 'B5', 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ['7', '1', '36', 'A5', 'Not Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=53222800', 'OH'],
       ['8', '1', '36', 'E3', 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57803010', 'TX']],
      dtype='<U69')

In [45]:
unique_subgrades = list(np.unique(loan_data_str[:,3]))
unique_subgrades

['A1',
 'A2',
 'A3',
 'A4',
 'A5',
 'B1',
 'B2',
 'B3',
 'B4',
 'B5',
 'C1',
 'C2',
 'C3',
 'C4',
 'C5',
 'D1',
 'D2',
 'D3',
 'D4',
 'D5',
 'E1',
 'E2',
 'E3',
 'E4',
 'E5',
 'F1',
 'F2',
 'F3',
 'F4',
 'F5',
 'G1',
 'G2',
 'G3',
 'G4',
 'G5',
 'H1']

In [46]:
unique_sg_values = list(range(1,len(unique_subgrades) + 1))
unique_sg_values

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36]

In [47]:
subgrades_dict = dict(zip(unique_subgrades, unique_sg_values))

In [48]:
subgrades_dict

{'A1': 1,
 'A2': 2,
 'A3': 3,
 'A4': 4,
 'A5': 5,
 'B1': 6,
 'B2': 7,
 'B3': 8,
 'B4': 9,
 'B5': 10,
 'C1': 11,
 'C2': 12,
 'C3': 13,
 'C4': 14,
 'C5': 15,
 'D1': 16,
 'D2': 17,
 'D3': 18,
 'D4': 19,
 'D5': 20,
 'E1': 21,
 'E2': 22,
 'E3': 23,
 'E4': 24,
 'E5': 25,
 'F1': 26,
 'F2': 27,
 'F3': 28,
 'F4': 29,
 'F5': 30,
 'G1': 31,
 'G2': 32,
 'G3': 33,
 'G4': 34,
 'G5': 35,
 'H1': 36}

In [49]:
for key in subgrades_dict:
    loan_data_str[:,3] = np.where(loan_data_str[:,3] == key,
                                  subgrades_dict[key],
                                  loan_data_str[:,3])
loan_data_str[:,3]

array(['13', '5', '10', ..., '5', '17', '4'], dtype='<U69')

In [50]:
np.unique(loan_data_str[:,3])

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22',
       '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36',
       '4', '5', '6', '7', '8', '9'], dtype='<U69')

### String - Verification Status and URL

In [51]:
np.unique(loan_data_str[:,4], return_counts=True, return_index=True)

(array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69'),
 array([7, 3, 1, 0], dtype=int64),
 array([ 500, 2673, 4116, 2711], dtype=int64))

In [52]:
loan_data_str[:,4] = np.where((loan_data_str[:,4]=='') | (loan_data_str[:,4]=='Not Verified'), 0, 1)
np.unique(loan_data_str[:,4], return_counts=True, return_index=True)

(array(['0', '1'], dtype='<U69'),
 array([3, 0], dtype=int64),
 array([3173, 6827], dtype=int64))

In [53]:
str_headers

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [54]:
loan_data_str[:,5]

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', ...,
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249'], dtype='<U69')

In [55]:
str_ids = np.chararray.strip(loan_data_str[:,5], 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=')
str_ids

chararray(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'],
          dtype='<U69')

In [56]:
numeric_ids = loan_data_numeric[:,0]
numeric_ids

array([48010226., 57693261., 59432726., ..., 50415990., 46154151., 66055249.])

In [57]:
str_ids

chararray(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'],
          dtype='<U69')

In [58]:
print(str_ids)

['48010226' '57693261' '59432726' ... '50415990' '46154151' '66055249']


In [59]:
type(str_ids)

numpy.chararray

In [60]:
str_ids = np.array(str_ids)
str_ids

array(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'], dtype='<U69')

In [61]:
np.array_equal(str_ids.astype(np.int32), numeric_ids)

True

In [62]:
loan_data_str[0]

array(['5', '1', '36', '13', '1',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'], dtype='<U69')

In [63]:
str_headers

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [64]:
loan_data_str = np.delete(loan_data_str, [5], axis=1)
str_headers = np.delete(str_headers, [5])

In [65]:
loan_data_str[0]

array(['5', '1', '36', '13', '1', 'CA'], dtype='<U69')

In [66]:
str_headers

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'addr_state'], dtype='<U19')

### String - State Address

In [67]:
np.unique(loan_data_str[:,5])

array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
       'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
       'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
       'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69')

In [68]:
np.unique(loan_data_str[:,5]).size

50

In [69]:
str_headers[5] = 'state_address'

In [70]:
np.unique(loan_data_str[:,5], return_counts=True)

(array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
        'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
        'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
        'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69'),
 array([ 500,   26,  119,   74,  220, 1336,  201,  143,   27,   27,  690,  321,   44,  389,  152,
          84,   84,  116,  210,  222,   10,  267,  156,  160,   61,   28,  261,   16,   25,   58,
         341,   57,  130,  777,  312,   83,  108,  320,   40,  107,   24,  143,  758,   74,  242,
          17,  216,  148,   49,   27], dtype=int64))

In [71]:
states, state_counts = np.unique(loan_data_str[:,5], return_counts=True)
state_counts_desc_index = np.argsort(-state_counts)
states[state_counts_desc_index], state_counts[state_counts_desc_index]

(array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI', 'NC', 'VA', 'MD', 'AZ',
        'WA', 'MA', 'CO', 'MO', 'MN', 'IN', 'WI', 'CT', 'TN', 'NV', 'AL', 'LA', 'OR', 'SC', 'KY',
        'KS', 'OK', 'UT', 'AR', 'MS', 'NH', 'NM', 'WV', 'HI', 'RI', 'MT', 'DE', 'DC', 'WY', 'AK',
        'NE', 'SD', 'VT', 'ND', 'ME'], dtype='<U69'),
 array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,  261,  242,  222,  220,
         216,  210,  201,  160,  156,  152,  148,  143,  143,  130,  119,  116,  108,  107,   84,
          84,   83,   74,   74,   61,   58,   57,   49,   44,   40,   28,   27,   27,   27,   26,
          25,   24,   17,   16,   10], dtype=int64))

In [72]:
loan_data_str[:,5] = np.where(loan_data_str[:,5] == '', 0, loan_data_str[:,5])

In [73]:
states_west = np.array(['WA', 'OR','CA','NV','ID','MT', 'WY','UT','CO', 'AZ','NM','HI','AK'])
states_south = np.array(['TX','OK','AR','LA','MS','AL','TN','KY','FL','GA','SC','NC','VA','WV','MD','DE','DC'])
states_midwest = np.array(['ND','SD','NE','KS','MN','IA','MO','WI','IL','IN','MI','OH'])
states_east = np.array(['PA','NY','NJ','CT','MA','VT','NH','ME','RI'])

In [74]:
loan_data_str[:,5] = np.where(np.isin(loan_data_str[:,5], states_west), 1, loan_data_str[:,5])
loan_data_str[:,5] = np.where(np.isin(loan_data_str[:,5], states_south), 2, loan_data_str[:,5])
loan_data_str[:,5] = np.where(np.isin(loan_data_str[:,5], states_midwest), 3, loan_data_str[:,5])
loan_data_str[:,5] = np.where(np.isin(loan_data_str[:,5], states_east), 4, loan_data_str[:,5])

In [75]:
np.unique(loan_data_str[:,5])

array(['0', '1', '2', '3', '4'], dtype='<U69')

### Converting string array to numeric array

In [76]:
loan_data_str

array([['5', '1', '36', '13', '1', '1'],
       ['0', '1', '36', '5', '1', '4'],
       ['9', '1', '36', '10', '1', '4'],
       ...,
       ['6', '1', '36', '5', '1', '1'],
       ['4', '1', '36', '17', '1', '3'],
       ['12', '1', '36', '4', '0', '3']], dtype='<U69')

In [77]:
str_headers

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'state_address'], dtype='<U19')

In [78]:
type(loan_data_numeric[0][0])

numpy.float64

In [79]:
loan_data_str = loan_data_str.astype(np.int)
print(loan_data_str)

[[ 5  1 36 13  1  1]
 [ 0  1 36  5  1  4]
 [ 9  1 36 10  1  4]
 ...
 [ 6  1 36  5  1  1]
 [ 4  1 36 17  1  3]
 [12  1 36  4  0  3]]


<ipython-input-79-6918ecdc1733>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  loan_data_str = loan_data_str.astype(np.int)


In [80]:
type(loan_data_str[0][0])

numpy.int32

In [81]:
loan_data_str_backup = create_backup('loan-data-str-backup', str_headers, loan_data_str)

In [82]:
loan_data_str_backup['data']

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

In [83]:
np.array_equal(loan_data_str, loan_data_str_backup['data'])

True

## Manipulating Numeric Data

In [84]:
temporary_fill

68616520.0

In [85]:
print(temporary_stats)

[[  373332.           nan     1000.           nan     1000.           nan        6.         31.42
          nan         nan         nan         nan         nan        0.  ]
 [54015809.19         nan    15273.46         nan    15311.04         nan       16.62      440.92
          nan         nan         nan         nan         nan     3143.85]
 [68616519.           nan    35000.           nan    35000.           nan       28.99     1372.97
          nan         nan         nan         nan         nan    41913.62]]


In [86]:
print(numeric_col_ids)

[ 0  2  4  6  7 13]


In [87]:
print(str_col_ids)

[ 1  3  5  8  9 10 11 12]


In [88]:
print(all_headers)

['id' 'issue_d' 'loan_amnt' 'loan_status' 'funded_amnt' 'term' 'int_rate' 'installment' 'grade'
 'sub_grade' 'verification_status' 'url' 'addr_state' 'total_pymnt']


In [89]:
print(numeric_headers)

['id' 'loan_amnt' 'funded_amnt' 'int_rate' 'installment' 'total_pymnt']


In [90]:
print(loan_data_numeric)

[[48010226.      35000.      35000.         13.33     1184.86     9452.96]
 [57693261.      30000.      30000.   68616520.        938.57     4679.7 ]
 [59432726.      15000.      15000.   68616520.        494.86     1969.83]
 ...
 [50415990.      10000.      10000.   68616520.   68616520.       2185.64]
 [46154151.   68616520.      10000.         16.55      354.3      3199.4 ]
 [66055249.      10000.      10000.   68616520.        309.97      301.9 ]]


In [91]:
np.isnan(loan_data_numeric).sum()

0

### ID

In [92]:
np.isin(temporary_fill, loan_data_numeric[:,0])

array(False)

In [93]:
numeric_stats = temporary_stats[:,numeric_col_ids]
print(numeric_stats)

[[  373332.       1000.       1000.          6.         31.42        0.  ]
 [54015809.19    15273.46    15311.04       16.62      440.92     3143.85]
 [68616519.      35000.      35000.         28.99     1372.97    41913.62]]


### Funded Amount

In [94]:
np.isin(temporary_fill, loan_data_numeric[:,2])

array(True)

In [95]:
fa_temp_fill_index = np.argwhere(loan_data_numeric[:,2] == temporary_fill).squeeze()

In [96]:
fa_temp_fill_index.size

500

In [97]:
print(fa_temp_fill_index)

[  57   58   59   85  100  145  161  218  236  240  262  279  297  303  306  365  374  377  397
  427  468  481  498  544  556  568  576  580  588  635  669  734  742  750  789  794  798  809
  818  819  840  846  860  864  871  917  958  973  979  985  994 1005 1007 1075 1085 1088 1149
 1160 1178 1186 1199 1203 1204 1215 1226 1230 1237 1245 1268 1281 1283 1294 1324 1325 1330 1344
 1384 1409 1419 1431 1481 1493 1504 1545 1561 1588 1618 1627 1632 1633 1653 1668 1676 1677 1688
 1701 1706 1757 1810 1834 1835 1888 1899 1911 1925 1933 2019 2067 2068 2086 2087 2147 2185 2205
 2213 2278 2298 2306 2309 2327 2372 2381 2488 2493 2534 2535 2542 2576 2604 2609 2642 2658 2677
 2707 2714 2719 2758 2793 2824 2825 2835 2839 2869 2873 2878 2902 2921 2949 2957 2959 2974 2994
 3014 3018 3031 3090 3115 3121 3122 3125 3149 3162 3192 3203 3268 3272 3313 3334 3337 3342 3362
 3365 3366 3393 3397 3416 3442 3483 3508 3513 3616 3627 3694 3700 3715 3742 3750 3768 3838 3901
 3916 3926 3935 3956 3959 3988 4001 4021

In [98]:
loan_data_numeric[9600][2]

68616520.0

In [99]:
loan_data_numeric[:,2] = np.where(loan_data_numeric[:,2] == temporary_fill,
                                  numeric_stats[0][2],
                                  loan_data_numeric[:,2])
print(loan_data_numeric)

[[48010226.      35000.      35000.         13.33     1184.86     9452.96]
 [57693261.      30000.      30000.   68616520.        938.57     4679.7 ]
 [59432726.      15000.      15000.   68616520.        494.86     1969.83]
 ...
 [50415990.      10000.      10000.   68616520.   68616520.       2185.64]
 [46154151.   68616520.      10000.         16.55      354.3      3199.4 ]
 [66055249.      10000.      10000.   68616520.        309.97      301.9 ]]


In [100]:
np.isin(temporary_fill, loan_data_numeric[:,2])

array(False)

In [101]:
loan_data_numeric[6087][2]

1000.0

### Loan amount, interest rate, installment, total payment

In [102]:
numeric_headers

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [103]:
high_fill_index = [1,3,4,5]

In [104]:
for i in high_fill_index:
    loan_data_numeric[:,i] = np.where(loan_data_numeric[:,i] == temporary_fill,
                                      numeric_stats[2][i],
                                      loan_data_numeric[:,i])

### Exchange Rate

In [105]:
print(numeric_headers)

['id' 'loan_amnt' 'funded_amnt' 'int_rate' 'installment' 'total_pymnt']


In [106]:
EUR_USD = np.genfromtxt('EUR-USD.csv', delimiter=',', skip_header=1, usecols=[3])
print(EUR_USD)

[1.13 1.12 1.08 1.11 1.1  1.12 1.09 1.13 1.13 1.1  1.06 1.09]


In [107]:
str_headers

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'state_address'], dtype='<U19')

In [108]:
loan_data_str[:,0]

array([ 5,  0,  9, ...,  6,  4, 12])

In [109]:
account_ex_rates = loan_data_str[:,0]

for i in range(1,13):
    account_ex_rates = np.where(account_ex_rates == i,
                                EUR_USD[i-1],
                                account_ex_rates)

In [110]:
account_ex_rates = np.where(account_ex_rates == 0,
                            np.mean(EUR_USD),
                            account_ex_rates)

In [111]:
account_ex_rates

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [112]:
loan_data_numeric = np.hstack((loan_data_numeric, np.array([account_ex_rates]).transpose()))

In [113]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,     1184.86,     9452.96,        1.1 ],
       [57693261.  ,    30000.  ,    30000.  , ...,      938.57,     4679.7 ,        1.11],
       [59432726.  ,    15000.  ,    15000.  , ...,      494.86,     1969.83,        1.13],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     1372.97,     2185.64,        1.12],
       [46154151.  ,    35000.  ,    10000.  , ...,      354.3 ,     3199.4 ,        1.11],
       [66055249.  ,    10000.  ,    10000.  , ...,      309.97,      301.9 ,        1.09]])

In [114]:
numeric_headers

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [115]:
numeric_headers = np.concatenate((numeric_headers, np.array(['exchange_rate'])))
numeric_headers

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

In [116]:
loan_data_numeric_backup = create_backup('loan-data-numeric-backup', numeric_headers, loan_data_numeric)

### Using Exchange Rates

In [117]:
amount_col_index = np.array([1,2,4,5])

In [118]:
for i in amount_col_index:
    EUR_row = loan_data_numeric[:,i] / loan_data_numeric[:,6]
    EUR_column = np.reshape(EUR_row, (10000,1))
    loan_data_numeric = np.hstack((loan_data_numeric, EUR_column))

In [119]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1081.04,     8624.69],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
       [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      439.64,     1750.04],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,     1223.36,     1947.47],
       [46154151.  ,    35000.  ,    10000.  , ...,     8997.4 ,      318.78,     2878.63],
       [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      283.49,      276.11]])

In [120]:
loan_data_numeric.shape

(10000, 11)

In [121]:
numeric_extra_headers = np.array(['loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'])
numeric_headers = np.concatenate((numeric_headers, numeric_extra_headers))
numeric_headers

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate',
       'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U19')

In [122]:
for i in amount_col_index:
    numeric_headers[i] = numeric_headers[i] + '_USD'

In [123]:
numeric_headers

array(['id', 'loan_amnt_USD', 'funded_amnt_USD', 'int_rate', 'installment_USD', 'total_pymnt_USD',
       'exchange_rate', 'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'],
      dtype='<U19')

### Rearranging

In [124]:
col_order = [0,1,7,2,8,3,4,9,5,10,6]

In [125]:
numeric_headers = numeric_headers[col_order]

In [126]:
numeric_headers

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

In [127]:
loan_data_numeric[0]

array([48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96,        1.1 ,
          31933.3 ,    31933.3 ,     1081.04,     8624.69])

In [128]:
loan_data_numeric[:,col_order][0]

array([48010226.  ,    35000.  ,    31933.3 ,    35000.  ,    31933.3 ,       13.33,     1184.86,
           1081.04,     9452.96,     8624.69,        1.1 ])

In [129]:
loan_data_numeric = loan_data_numeric[:,col_order]
loan_data_numeric

array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
       [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
       [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
       [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,     2878.63,        1.11],
       [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]])

### Rate of Interest

In [130]:
loan_data_numeric[:,5]

array([13.33, 28.99, 28.99, ..., 28.99, 16.55, 28.99])

In [131]:
loan_data_numeric[:,5] = loan_data_numeric[:,5] / 100
loan_data_numeric[:,5]

array([0.13, 0.29, 0.29, ..., 0.29, 0.17, 0.29])

### Creating numeric data backup

In [132]:
loan_data_numeric_backup = create_backup('loan-data-numeric-backup', numeric_headers, loan_data_numeric)

### Attaching Numeric and String tables

In [133]:
loan_data_str_backup['data'].shape

(10000, 6)

In [134]:
loan_data_numeric_backup['data'].shape

(10000, 11)

In [135]:
loan_data = np.hstack((loan_data_numeric_backup['data'], loan_data_str_backup['data']))
loan_data

array([[48010226.  ,    35000.  ,    31933.3 , ...,       13.  ,        1.  ,        1.  ],
       [57693261.  ,    30000.  ,    27132.46, ...,        5.  ,        1.  ,        4.  ],
       [59432726.  ,    15000.  ,    13326.3 , ...,       10.  ,        1.  ,        4.  ],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,        5.  ,        1.  ,        1.  ],
       [46154151.  ,    35000.  ,    31490.9 , ...,       17.  ,        1.  ,        3.  ],
       [66055249.  ,    10000.  ,     9145.8 , ...,        4.  ,        0.  ,        3.  ]])

In [136]:
loan_data.shape

(10000, 17)

In [137]:
header_full = np.concatenate((loan_data_numeric_backup['headers'], loan_data_str_backup['headers']))
header_full

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate',
       'issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'state_address'], dtype='<U19')

### Sorting the entire dataset by ID

In [138]:
ID_ordered_index = np.argsort(loan_data[:,0])

In [139]:
ID_ordered_index

array([2086, 4812, 2353, ..., 4935, 9388, 8415], dtype=int64)

In [140]:
loan_data[2086]

array([373332.  ,   9950.  ,   9038.08,   1000.  ,    908.35,      0.18,    360.97,    327.89,
         1072.82,    974.5 ,      1.1 ,     10.  ,      1.  ,     36.  ,     21.  ,      0.  ,
            1.  ])

In [141]:
loan_data[ID_ordered_index]

array([[  373332.  ,     9950.  ,     9038.08, ...,       21.  ,        0.  ,        1.  ],
       [  575239.  ,    12000.  ,    10900.2 , ...,       25.  ,        1.  ,        2.  ],
       [  707689.  ,    10000.  ,     8924.3 , ...,       13.  ,        1.  ,        0.  ],
       ...,
       [68614880.  ,     5600.  ,     5121.65, ...,        8.  ,        1.  ,        1.  ],
       [68615915.  ,     4000.  ,     3658.32, ...,       10.  ,        1.  ,        2.  ],
       [68616519.  ,    21600.  ,    19754.93, ...,        3.  ,        0.  ,        2.  ]])

In [142]:
loan_data[ID_ordered_index][0]

array([373332.  ,   9950.  ,   9038.08,   1000.  ,    908.35,      0.18,    360.97,    327.89,
         1072.82,    974.5 ,      1.1 ,     10.  ,      1.  ,     36.  ,     21.  ,      0.  ,
            1.  ])

In [143]:
loan_data = loan_data[ID_ordered_index]
loan_data

array([[  373332.  ,     9950.  ,     9038.08, ...,       21.  ,        0.  ,        1.  ],
       [  575239.  ,    12000.  ,    10900.2 , ...,       25.  ,        1.  ,        2.  ],
       [  707689.  ,    10000.  ,     8924.3 , ...,       13.  ,        1.  ,        0.  ],
       ...,
       [68614880.  ,     5600.  ,     5121.65, ...,        8.  ,        1.  ,        1.  ],
       [68615915.  ,     4000.  ,     3658.32, ...,       10.  ,        1.  ,        2.  ],
       [68616519.  ,    21600.  ,    19754.93, ...,        3.  ,        0.  ,        2.  ]])

In [144]:
np.argsort(loan_data[:,0])

array([   0,    1,    2, ..., 9997, 9998, 9999], dtype=int64)

In [145]:
np.isnan(loan_data[:,0]).sum()

0

### Storing the array

In [146]:
print(header_full)

['id' 'loan_amnt_USD' 'loan_amnt_EUR' 'funded_amnt_USD' 'funded_amnt_EUR' 'int_rate'
 'installment_USD' 'installment_EUR' 'total_pymnt_USD' 'total_pymnt_EUR' 'exchange_rate'
 'issue_date' 'loan_status' 'term_months' 'sub_grade' 'verification_status' 'state_address']


In [147]:
print(loan_data)

[[  373332.       9950.       9038.08 ...       21.          0.          1.  ]
 [  575239.      12000.      10900.2  ...       25.          1.          2.  ]
 [  707689.      10000.       8924.3  ...       13.          1.          0.  ]
 ...
 [68614880.       5600.       5121.65 ...        8.          1.          1.  ]
 [68615915.       4000.       3658.32 ...       10.          1.          2.  ]
 [68616519.      21600.      19754.93 ...        3.          0.          2.  ]]


In [148]:
header_full.shape

(17,)

In [149]:
loan_data.shape

(10000, 17)

In [150]:
loan_data_preprocessed = np.vstack((header_full, loan_data))
loan_data_preprocessed

array([['id', 'loan_amnt_USD', 'loan_amnt_EUR', ..., 'sub_grade', 'verification_status',
        'state_address'],
       ['373332.0', '9950.0', '9038.082814338286', ..., '21.0', '0.0', '1.0'],
       ['575239.0', '12000.0', '10900.20037910145', ..., '25.0', '1.0', '2.0'],
       ...,
       ['68614880.0', '5600.0', '5121.647851612413', ..., '8.0', '1.0', '1.0'],
       ['68615915.0', '4000.0', '3658.319894008867', ..., '10.0', '1.0', '2.0'],
       ['68616519.0', '21600.0', '19754.927427647883', ..., '3.0', '0.0', '2.0']], dtype='<U32')

In [151]:
np.save('loan-data-preprocessed', loan_data_preprocessed)

In [152]:
np.savetxt('loan-data-preprocessed.csv', loan_data_preprocessed, fmt='%s', delimiter=',')